ALTER TABLE deals ADD COLUMN IF NOT EXISTS property_count_range VARCHAR(20);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS current_system VARCHAR(100);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS pain_point VARCHAR(255);
ALTER TABLE deals ADD COLUMN IF NOT EXISTS lead_source VARCHAR(50);
